# Generated by Django 5.0.6 on 2024-05-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=2)),
                ('numero_cedula', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicio_permiiso', models.DateField()),
                ('fecha_fin_permiso', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_solicitud', models.ImageField(blank=True, null=True, upload_to='solicitudes/')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.docente')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.sede'),
        ),
    ]
