# Generated by Django 5.0.6 on 2024-12-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='permiso',
            old_name='fecha_inicio_permiiso',
            new_name='fecha_inicio_permiso',
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='escuela',
            field=models.ForeignKey(default='LA MILAGROSA', on_delete=django.db.models.deletion.CASCADE, to='login.sede'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
    ]
