# Generated by Django 6.0 on 2025-12-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_docente_options_alter_sede_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
